import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { StyleSheet, type StyleProp, type ViewStyle } from 'react-native';
import { useTheme } from 'react-native-paper';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';

import type { AnswerIndex, Question } from '@/types';
import {
  createQuizPlayerUpdateScript,
  renderQuizPlayerShell,
  renderQuizReviewDocument,
  type QuizHtmlColors,
} from '@/utils/quizHtml';

interface SharedProps {
  question: Question;
  answer: AnswerIndex | null;
  style?: StyleProp<ViewStyle>;
  fill?: boolean;
}

type QuizQuestionContentProps = SharedProps & (
  | {
    variant: 'player';
    revealAnswer: boolean;
    locked: boolean;
    onSelect: (answer: AnswerIndex) => void;
  }
  | {
    variant: 'review';
  }
);

function QuizQuestionContentComponent(props: QuizQuestionContentProps) {
  const theme = useTheme();
  const { variant, question, answer } = props;
  const revealAnswer = variant === 'player' ? props.revealAnswer : false;
  const locked = variant === 'player' ? props.locked : true;
  const webViewRef = useRef<WebView>(null);
  const colors = useMemo<QuizHtmlColors>(() => ({
    surface: theme.colors.surface,
    surfaceVariant: theme.colors.surfaceVariant,
    onSurface: theme.colors.onSurface,
    onSurfaceVariant: theme.colors.onSurfaceVariant,
    outline: theme.colors.outline,
    outlineVariant: theme.colors.outlineVariant,
    primary: theme.colors.primary,
    primaryContainer: theme.colors.primaryContainer,
    onPrimaryContainer: theme.colors.onPrimaryContainer,
    error: theme.colors.error,
    errorContainer: theme.colors.errorContainer,
    onErrorContainer: theme.colors.onErrorContainer,
  }), [theme.colors]);

  const playerShellHtml = useMemo(() => renderQuizPlayerShell(colors), [colors]);
  const reviewHtml = useMemo(() => variant === 'review'
    ? renderQuizReviewDocument({
      question,
      answer,
      colors,
    })
    : '', [answer, colors, question, variant]);
  const html = variant === 'player' ? playerShellHtml : reviewHtml;
  const source = useMemo(() => ({ html }), [html]);
  const playerUpdateScript = useMemo(() => variant === 'player'
    ? createQuizPlayerUpdateScript({ question, selected: answer, revealAnswer, locked })
    : '', [answer, locked, question, revealAnswer, variant]);
  const estimatedReviewHeight = useMemo(() => {
    const answerLength = answer === null ? 7 : question.options[answer].length;
    const correctLength = answer === question.correctAnswer ? 0 : question.options[question.correctAnswer].length;
    const contentLength = question.prompt.length + answerLength + correctLength + question.explanation.length;
    return Math.min(900, Math.max(250, 185 + Math.ceil(contentLength / 34) * 22));
  }, [answer, question]);
  const [reviewHeight, setReviewHeight] = useState(estimatedReviewHeight);

  useEffect(() => {
    if (variant === 'review') setReviewHeight(estimatedReviewHeight);
  }, [estimatedReviewHeight, question.id, variant]);

  useEffect(() => {
    if (variant === 'player') webViewRef.current?.injectJavaScript(playerUpdateScript);
  }, [playerUpdateScript, variant]);

  const onMessage = useCallback((event: WebViewMessageEvent) => {
    try {
      const payload = JSON.parse(event.nativeEvent.data) as {
        type?: unknown;
        questionId?: unknown;
        answer?: unknown;
        height?: unknown;
      };
      if (
        props.variant === 'review'
        && payload.type === 'height'
        && payload.questionId === props.question.id
        && typeof payload.height === 'number'
        && Number.isFinite(payload.height)
      ) {
        const measured = Math.min(1400, Math.max(180, Math.ceil(payload.height) + 2));
        setReviewHeight((current) => Math.abs(current - measured) > 1 ? measured : current);
        return;
      }
      if (props.variant !== 'player') return;
      if (
        payload.type === 'select'
        && payload.questionId === props.question.id
        && typeof payload.answer === 'number'
        && Number.isInteger(payload.answer)
        && payload.answer >= 0
        && payload.answer <= 3
      ) {
        props.onSelect(payload.answer as AnswerIndex);
      }
    } catch {
      // Ignore messages that are not generated by the local quiz document.
    }
  }, [props]);

  return (
    <WebView
      ref={webViewRef}
      originWhitelist={['about:blank']}
      source={source}
      style={[
        styles.webView,
        props.variant === 'player' || props.fill ? styles.player : { height: reviewHeight },
        props.style,
      ]}
      containerStyle={styles.container}
      javaScriptEnabled
      domStorageEnabled={false}
      cacheEnabled
      scrollEnabled={props.variant === 'player'}
      nestedScrollEnabled={props.variant === 'player'}
      bounces={false}
      overScrollMode="never"
      showsHorizontalScrollIndicator={false}
      showsVerticalScrollIndicator={false}
      setSupportMultipleWindows={false}
      textZoom={100}
      onLoadEnd={() => {
        if (variant === 'player') webViewRef.current?.injectJavaScript(playerUpdateScript);
      }}
      onMessage={onMessage}
    />
  );
}

export const QuizQuestionContent = memo(QuizQuestionContentComponent);

const styles = StyleSheet.create({
  container: { backgroundColor: 'transparent' },
  webView: { alignSelf: 'stretch', backgroundColor: 'transparent' },
  player: { flex: 1 },
});
