import { memo, useCallback, useMemo } from 'react';
import { StyleSheet, useWindowDimensions, type StyleProp, type ViewStyle } from 'react-native';
import { useTheme } from 'react-native-paper';
import { WebView, type WebViewMessageEvent } from 'react-native-webview';

import type { AnswerIndex, Question } from '@/types';
import {
  renderQuizPlayerDocument,
  renderQuizReviewDocument,
  type QuizHtmlColors,
} from '@/utils/quizHtml';

interface SharedProps {
  question: Question;
  answer: AnswerIndex | null;
  style?: StyleProp<ViewStyle>;
  fill?: boolean;
}

type QuizQuestionContentProps = SharedProps & (
  | {
    variant: 'player';
    revealAnswer: boolean;
    locked: boolean;
    onSelect: (answer: AnswerIndex) => void;
  }
  | {
    variant: 'review';
  }
);

function QuizQuestionContentComponent(props: QuizQuestionContentProps) {
  const theme = useTheme();
  const window = useWindowDimensions();
  const { variant, question, answer } = props;
  const revealAnswer = variant === 'player' ? props.revealAnswer : false;
  const locked = variant === 'player' ? props.locked : true;
  const colors = useMemo<QuizHtmlColors>(() => ({
    surface: theme.colors.surface,
    surfaceVariant: theme.colors.surfaceVariant,
    onSurface: theme.colors.onSurface,
    onSurfaceVariant: theme.colors.onSurfaceVariant,
    outline: theme.colors.outline,
    outlineVariant: theme.colors.outlineVariant,
    primary: theme.colors.primary,
    primaryContainer: theme.colors.primaryContainer,
    onPrimaryContainer: theme.colors.onPrimaryContainer,
    error: theme.colors.error,
    errorContainer: theme.colors.errorContainer,
    onErrorContainer: theme.colors.onErrorContainer,
  }), [theme.colors]);

  const html = useMemo(() => variant === 'player'
    ? renderQuizPlayerDocument({
      question,
      selected: answer,
      revealAnswer,
      locked,
      colors,
    })
    : renderQuizReviewDocument({
      question,
      answer,
      colors,
    }), [answer, colors, locked, question, revealAnswer, variant]);
  const source = useMemo(() => ({ html }), [html]);

  const onMessage = useCallback((event: WebViewMessageEvent) => {
    if (props.variant !== 'player') return;
    try {
      const payload = JSON.parse(event.nativeEvent.data) as {
        type?: unknown;
        questionId?: unknown;
        answer?: unknown;
      };
      if (
        payload.type === 'select'
        && payload.questionId === props.question.id
        && typeof payload.answer === 'number'
        && Number.isInteger(payload.answer)
        && payload.answer >= 0
        && payload.answer <= 3
      ) {
        props.onSelect(payload.answer as AnswerIndex);
      }
    } catch {
      // Ignore messages that are not generated by the local quiz document.
    }
  }, [props]);

  const reviewHeight = Math.min(580, Math.max(410, Math.round(window.height * 0.62)));

  return (
    <WebView
      key={`${props.variant}-${props.question.id}`}
      originWhitelist={['about:blank']}
      source={source}
      style={[
        styles.webView,
        props.variant === 'player' || props.fill ? styles.player : { height: reviewHeight },
        props.style,
      ]}
      containerStyle={styles.container}
      javaScriptEnabled={props.variant === 'player'}
      domStorageEnabled={false}
      cacheEnabled={false}
      scrollEnabled
      nestedScrollEnabled
      bounces={false}
      overScrollMode="never"
      showsHorizontalScrollIndicator={false}
      showsVerticalScrollIndicator={false}
      setSupportMultipleWindows={false}
      textZoom={100}
      onMessage={onMessage}
      accessibilityLabel={props.variant === 'player' ? 'Quiz question and answer choices' : 'Answer review'}
    />
  );
}

export const QuizQuestionContent = memo(QuizQuestionContentComponent);

const styles = StyleSheet.create({
  container: { backgroundColor: 'transparent' },
  webView: { alignSelf: 'stretch', backgroundColor: 'transparent' },
  player: { flex: 1 },
});
